// Code generated by MockGen. DO NOT EDIT.
// Source: esad/internal/controller/ad (interfaces: Controller)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	ad "esad/internal/entity/ad"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockController is a mock of Controller interface
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// CreateAnomalyDetector mocks base method
func (m *MockController) CreateAnomalyDetector(arg0 context.Context, arg1 ad.CreateDetectorRequest) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnomalyDetector", arg0, arg1)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAnomalyDetector indicates an expected call of CreateAnomalyDetector
func (mr *MockControllerMockRecorder) CreateAnomalyDetector(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnomalyDetector", reflect.TypeOf((*MockController)(nil).CreateAnomalyDetector), arg0, arg1)
}

// CreateMultiEntityAnomalyDetector mocks base method
func (m *MockController) CreateMultiEntityAnomalyDetector(arg0 context.Context, arg1 ad.CreateDetectorRequest, arg2, arg3 bool) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultiEntityAnomalyDetector", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultiEntityAnomalyDetector indicates an expected call of CreateMultiEntityAnomalyDetector
func (mr *MockControllerMockRecorder) CreateMultiEntityAnomalyDetector(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiEntityAnomalyDetector", reflect.TypeOf((*MockController)(nil).CreateMultiEntityAnomalyDetector), arg0, arg1, arg2, arg3)
}

// DeleteDetector mocks base method
func (m *MockController) DeleteDetector(arg0 context.Context, arg1 string, arg2, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDetector", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDetector indicates an expected call of DeleteDetector
func (mr *MockControllerMockRecorder) DeleteDetector(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDetector", reflect.TypeOf((*MockController)(nil).DeleteDetector), arg0, arg1, arg2, arg3)
}

// DeleteDetectorByName mocks base method
func (m *MockController) DeleteDetectorByName(arg0 context.Context, arg1 string, arg2, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDetectorByName", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDetectorByName indicates an expected call of DeleteDetectorByName
func (mr *MockControllerMockRecorder) DeleteDetectorByName(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDetectorByName", reflect.TypeOf((*MockController)(nil).DeleteDetectorByName), arg0, arg1, arg2, arg3)
}

// GetDetector mocks base method
func (m *MockController) GetDetector(arg0 context.Context, arg1 string) (*ad.DetectorOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetector", arg0, arg1)
	ret0, _ := ret[0].(*ad.DetectorOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetector indicates an expected call of GetDetector
func (mr *MockControllerMockRecorder) GetDetector(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetector", reflect.TypeOf((*MockController)(nil).GetDetector), arg0, arg1)
}

// GetDetectorsByName mocks base method
func (m *MockController) GetDetectorsByName(arg0 context.Context, arg1 string, arg2 bool) ([]*ad.DetectorOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetectorsByName", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*ad.DetectorOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetectorsByName indicates an expected call of GetDetectorsByName
func (mr *MockControllerMockRecorder) GetDetectorsByName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetectorsByName", reflect.TypeOf((*MockController)(nil).GetDetectorsByName), arg0, arg1, arg2)
}

// SearchDetectorByName mocks base method
func (m *MockController) SearchDetectorByName(arg0 context.Context, arg1 string) ([]ad.Detector, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDetectorByName", arg0, arg1)
	ret0, _ := ret[0].([]ad.Detector)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDetectorByName indicates an expected call of SearchDetectorByName
func (mr *MockControllerMockRecorder) SearchDetectorByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDetectorByName", reflect.TypeOf((*MockController)(nil).SearchDetectorByName), arg0, arg1)
}

// StartDetector mocks base method
func (m *MockController) StartDetector(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDetector", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartDetector indicates an expected call of StartDetector
func (mr *MockControllerMockRecorder) StartDetector(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDetector", reflect.TypeOf((*MockController)(nil).StartDetector), arg0, arg1)
}

// StartDetectorByName mocks base method
func (m *MockController) StartDetectorByName(arg0 context.Context, arg1 string, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDetectorByName", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartDetectorByName indicates an expected call of StartDetectorByName
func (mr *MockControllerMockRecorder) StartDetectorByName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDetectorByName", reflect.TypeOf((*MockController)(nil).StartDetectorByName), arg0, arg1, arg2)
}

// StopDetector mocks base method
func (m *MockController) StopDetector(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopDetector", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopDetector indicates an expected call of StopDetector
func (mr *MockControllerMockRecorder) StopDetector(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDetector", reflect.TypeOf((*MockController)(nil).StopDetector), arg0, arg1)
}

// StopDetectorByName mocks base method
func (m *MockController) StopDetectorByName(arg0 context.Context, arg1 string, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopDetectorByName", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopDetectorByName indicates an expected call of StopDetectorByName
func (mr *MockControllerMockRecorder) StopDetectorByName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDetectorByName", reflect.TypeOf((*MockController)(nil).StopDetectorByName), arg0, arg1, arg2)
}

// UpdateDetector mocks base method
func (m *MockController) UpdateDetector(arg0 context.Context, arg1 ad.UpdateDetectorUserInput, arg2, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDetector", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDetector indicates an expected call of UpdateDetector
func (mr *MockControllerMockRecorder) UpdateDetector(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDetector", reflect.TypeOf((*MockController)(nil).UpdateDetector), arg0, arg1, arg2, arg3)
}
