name: Publish AD CLI
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - name: Set up Go ubuntu-latest
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out AD CLI
        uses: actions/checkout@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --snapshot --skip-publish
          workdir: cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS(amd64) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: esad-darwin-amd64
          path: cli/dist/esad_darwin_amd64/esad

      - name: Upload Linux(amd64) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: esad-linux-amd64
          path: cli/dist/esad_linux_amd64/esad

      - name: Upload Linux(arm64) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: esad-linux-arm64
          path: cli/dist/esad_linux_arm64/esad

      - name: Upload Windows(i386) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: esad-windows-386
          path: cli/dist/esad_windows_386/esad.exe

      - name: Upload Windows(amd64) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: esad-windows-amd64
          path: cli/dist/esad_windows_amd64/esad.exe

